"""Simple helpers for 2D scatter plots."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/plot_scatter.ipynb.

# %% ../../nbs/plot_scatter.ipynb #e35c112b
from __future__ import annotations

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from matplotlib.axes import Axes


# %% auto #0
__all__ = ['plot_scatter']

# %% ../../nbs/plot_scatter.ipynb #8b366ec6
def plot_scatter(
    data: pd.DataFrame,
    x: str,
    y: str,
    hue: str | None = None,
    ax: Axes | None = None,
    title: str | None = None,
    size: int = 60,
    alpha: float = 0.8,
    **kwargs,
) -> Axes:
    """Plot a simple 2D scatter plot from a dataframe."""

    if ax is None:
        _, ax = plt.subplots(figsize=(6, 4))

    sns.scatterplot(
        data=data,
        x=x,
        y=y,
        hue=hue,
        s=size,
        alpha=alpha,
        ax=ax,
        **kwargs,
    )
    ax.set_title(title or f"{y} vs {x}")
    ax.set_xlabel(x)
    ax.set_ylabel(y)
    return ax

