# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kplot',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/kplot',
                'lib_path': 'kplot'},
  'syms': {'kplot.core': {'kplot.core.foo': ('core.html#foo', 'kplot/core.py')}}}
