"""Similarity, matrix, and confusion plots split from `08_all.ipynb`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_heatmap.ipynb.

# %% auto #0
__all__ = ['get_similarity', 'plot_corr', 'plot_confusion_matrix']

# %% ../nbs/04_heatmap.ipynb #62413717
import warnings

import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix, pairwise_distances

# %% ../nbs/04_heatmap.ipynb #98eab0ae
def get_similarity(
    df: pd.DataFrame,  # numeric feature matrix indexed by sample name
    metric: str = 'euclidean',  # pairwise_distances metric name
) -> tuple[pd.DataFrame, pd.DataFrame]:
    "Calculate both distance and similarity matrices for a dataframe."
    dist_matrix = pairwise_distances(df, metric=metric)
    dist_df = pd.DataFrame(dist_matrix, index=df.index, columns=df.index)
    sigma = float(np.mean(dist_matrix))
    if not np.isfinite(sigma) or np.isclose(sigma, 0.0):
        sim_df = pd.DataFrame(np.ones_like(dist_matrix, dtype=float), index=df.index, columns=df.index)
    else:
        sim_df = pd.DataFrame(np.exp(-(dist_matrix ** 2) / (2 * sigma ** 2)), index=df.index, columns=df.index)
    return dist_df, sim_df

# %% ../nbs/04_heatmap.ipynb #59f2ffc1
def plot_corr(
    df_corr: pd.DataFrame,  # correlation, distance, or similarity matrix
    mask_method: str | None = 'upper',  # upper, lower, or None
    inverse_color: bool = False,  # reverse the colormap when True
    figsize: tuple[float, float] = (15, 10),  # figure size in inches
    annot: bool = True,  # whether to annotate the matrix values
    linewidths: float = 0.1,  # cell border width
    **kwargs,  # forwarded heatmap kwargs
):
    "Plot a square matrix with an optional triangular mask." 
    if mask_method == 'upper':
        mask = np.triu(np.ones_like(df_corr, dtype=bool))
    elif mask_method == 'lower':
        mask = np.tril(np.ones_like(df_corr, dtype=bool))
    else:
        mask = None

    fig, ax = plt.subplots(figsize=figsize)
    sns.heatmap(
        df_corr,
        cmap='coolwarm_r' if inverse_color else 'coolwarm',
        mask=mask,
        annot=annot,
        fmt='.2f',
        linewidths=linewidths,
        linecolor='white',
        ax=ax,
        **kwargs,
    )
    ax.set_xlabel('')
    ax.set_ylabel('')
    plt.yticks(rotation=0)
    return ax

# %% ../nbs/04_heatmap.ipynb #eacf4054
def plot_confusion_matrix(
    target,  # true labels
    pred,  # predicted labels
    class_names: list[str] | None = None,  # labels shown on the axes
    normalize: bool = False,  # normalize rows when True
    title: str = 'Confusion matrix',  # plot title
    cmap=plt.cm.Blues,  # matplotlib colormap
    **kwargs,  # forwarded heatmap kwargs
):
    "Plot a confusion matrix from target and prediction arrays."
    observed_labels = pd.Index(pd.concat([pd.Series(target), pd.Series(pred)], ignore_index=True).dropna().unique()).tolist()
    if len(observed_labels) == 0:
        raise ValueError('target and pred must contain at least one non-null label')

    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", message=r"A single label was found in 'y_true' and 'y_pred'.*", category=UserWarning)
        cm = confusion_matrix(target, pred, labels=observed_labels)
    if normalize:
        row_sums = cm.sum(axis=1, keepdims=True)
        cm = np.divide(cm.astype(float), row_sums, out=np.zeros_like(cm, dtype=float), where=row_sums != 0)
        print('Normalized confusion matrix')
    else:
        print('Confusion matrix, without normalization')

    if class_names is None or len(class_names) != len(observed_labels):
        class_names = [str(label) for label in observed_labels]

    fig, ax = plt.subplots(figsize=(6, 6))
    sns.heatmap(cm, annot=True, fmt='.2f' if normalize else 'd', cmap=cmap, ax=ax, **kwargs)
    ax.set_title(title)
    ax.set_ylabel('True label')
    ax.set_xlabel('Predicted label')
    ax.set_xticks(np.arange(len(class_names)) + 0.5, class_names)
    ax.set_yticks(np.arange(len(class_names)) + 0.5, class_names)
    plt.yticks(rotation=0)
    return ax
