# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_hierarchical.ipynb.

# %% auto #0
__all__ = ['get_1d_distance', 'get_distance', 'get_1d_distance_parallel', 'get_Z', 'plot_dendrogram', 'get_hcluster']

# %% ../nbs/05_hierarchical.ipynb #7c11d571-dc85-4223-a245-c864c847b2e7
import pandas as pd,numpy as np,seaborn as sns
from tqdm import tqdm
from functools import partial
from tqdm.contrib.concurrent import process_map
from fastcore.meta import delegates
from scipy.cluster.hierarchy import fcluster,linkage,dendrogram
from scipy.spatial.distance import pdist, euclidean
from matplotlib import pyplot as plt
from cachetools import LRUCache

# %% ../nbs/05_hierarchical.ipynb #f79922a2-ec05-477a-88b4-39422b9da998
def get_1d_distance(df,func_flat):
    "Compute 1D distance (like pdist from scipy) but for df with column names"
    n = len(df)
    dist = []
    for i in tqdm(range(n)):
        for j in range(i+1, n):
            d = func_flat(df.iloc[i], df.iloc[j])
            dist.append(d)
    return np.array(dist)

# %% ../nbs/05_hierarchical.ipynb #33a0b685-79a8-4aa3-83e4-6bdc687343d4
def get_distance(pair, df, func):
    i,j=pair
    return func(df.iloc[i], df.iloc[j])

# %% ../nbs/05_hierarchical.ipynb #1b6e4e42-c27c-48b0-ac6b-fff654bc8eba
def get_1d_distance_parallel(df, func_flat, max_workers=4, chunksize=100):
    "Parallel compute 1D distance for each row in a dataframe given a distance function "
    n = len(df)
    index_pairs = [(i, j) for i in range(n) for j in range(i + 1, n)]

    bound_worker = partial(get_distance, df=df, func=func_flat)

    dist = process_map(bound_worker, index_pairs, max_workers=max_workers, chunksize=chunksize)
    return np.array(dist)

# %% ../nbs/05_hierarchical.ipynb #f4a202c1-c327-4064-90f6-e4a7dc624da4
_Z_CACHE = LRUCache(maxsize=50)

# %% ../nbs/05_hierarchical.ipynb #51fa5e1a-e354-4ca2-90eb-98a876cc7b7f
def get_Z(pssms,func_flat,method='ward',parallel=True):
    "Get linkage matrix Z from pssms dataframe"
    key = id(pssms)
    if key not in _Z_CACHE:
        distance = get_1d_distance_parallel(pssms,func_flat=func_flat) if parallel else get_1d_distance(pssms,func_flat=func_flat)
        Z = linkage(distance, method=method)
        _Z_CACHE[key] =Z
    return _Z_CACHE[key]

# %% ../nbs/05_hierarchical.ipynb #e4d4b7ab-4418-4400-ae51-a862e58e3e83
def plot_dendrogram(Z,
                    thr=0.07,
                    dense=4, # the higher the more dense for each row
                    line_width=1,
                    title=None,
                    scale=1,
                    **kwargs):
    length = (len(Z) + 1) // dense
    
    plt.figure(figsize=(5*scale,length*scale))
    with plt.rc_context({'lines.linewidth': line_width}):
        dendrogram(
            Z,
            orientation='left',
            leaf_font_size=7,
            color_threshold=thr,
            **kwargs
        )
    if title is not None: plt.title(title)
    plt.xlabel('Distance')
    # plt.savefig(output, bbox_inches='tight')
    # plt.close()
    ax = plt.gca()
    for spine in ['top', 'right', 'left', 'bottom']:
        ax.spines[spine].set_visible(False)

# %% ../nbs/05_hierarchical.ipynb #21c3b2a7-28fd-4901-a341-daf93a260329
def get_hcluster(df,thr=0.07,plot=True,labels=None,func_flat=euclidean,method='ward',**kwargs):
    "Get flat cluster assignments from hierarchical clustering linkage matrix `Z`."
    Z = get_Z(df,func_flat=func_flat,method=method)
    if plot: plot_dendrogram(Z,labels=labels if labels is not None else df.index,thr=thr,**kwargs)
    clusters = fcluster(Z, thr, criterion='distance')
    return pd.Series(clusters, index=df.index)
