"""General plotting helpers, save utilities, and palette/color tools."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_utils.ipynb.

# %% auto #0
__all__ = ['set_sns', 'save_svg', 'save_pdf', 'save_show', 'get_color_dict', 'get_plt_color', 'get_hue_big', 'add_stats']

# %% ../nbs/01_utils.ipynb #ddc75e41
import itertools
from itertools import cycle
from pathlib import Path

import matplotlib as mpl
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from statannotations.Annotator import Annotator

# %% ../nbs/01_utils.ipynb #45ce2a1b
def set_sns(dpi: int = 300) -> None:
    "Set seaborn defaults for notebook display and saved figures."
    sns.set(rc={"figure.dpi": dpi, "savefig.dpi": dpi})
    sns.set_context('notebook')
    sns.set_style('ticks')

# %% ../nbs/01_utils.ipynb #e9e9554e
def save_svg(path: str | Path) -> None:
    "Save the current matplotlib figure as SVG with editable text."
    plt.rcParams['svg.fonttype'] = 'none'
    plt.savefig(path, format='svg', bbox_inches='tight', transparent=True)

# %% ../nbs/01_utils.ipynb #3bc16a3d
def save_pdf(path: str | Path) -> None:
    "Save the current matplotlib figure as PDF with TrueType fonts."
    mpl.rcParams['pdf.fonttype'] = 42
    mpl.rcParams['ps.fonttype'] = 42
    plt.savefig(path, format='pdf', bbox_inches='tight', transparent=True)

# %% ../nbs/01_utils.ipynb #a2f2169c
def save_show(
    path: str | Path | None = None,  # output path when saving instead of showing
    show_only: bool = False,  # force plt.show even when no path is provided
) -> None:
    "Show the current figure or save it, then close open figures."
    if show_only:
        plt.show()
    elif path is not None:
        plt.savefig(path, bbox_inches='tight', pad_inches=0.05, transparent=True)
    else:
        plt.show()
    plt.close('all')

# %% ../nbs/01_utils.ipynb #932b606c
def get_color_dict(
    categories: list[str],  # labels that need colors
    palette: str = 'tab20',  # seaborn palette name
) -> dict[str, tuple[float, float, float]]:
    "Assign colors to labels while tolerating duplicate category names."
    colors = sns.color_palette(palette)
    color_cycle = cycle(colors)
    return {category: next(color_cycle) for category in categories}

# %% ../nbs/01_utils.ipynb #311655d2
def get_plt_color(
    palette: dict | list | str,  # dict lookup, explicit list, or palette name
    columns: list[str],  # plotted column names in output order
) -> list:
    "Return colors in plotting order for a dict, list, or named palette."
    if isinstance(palette, dict):
        return [palette.get(col, '#cccccc') for col in columns]
    if isinstance(palette, str):
        return sns.color_palette(palette, n_colors=len(columns))
    if isinstance(palette, list):
        return palette
    raise TypeError('palette must be a dict, list, or seaborn palette name')

# %% ../nbs/01_utils.ipynb #983766a1
def get_hue_big(
    df: pd.DataFrame,  # source dataframe
    hue_col: str,  # categorical column used for hue
    cnt_thr: int = 10,  # minimum count retained in the filtered hue series
) -> pd.Series:
    "Filter a hue column down to categories that meet a count threshold."
    counts = df[hue_col].value_counts()
    keep = counts[counts >= cnt_thr].index
    return df[hue_col][df[hue_col].isin(keep)]

# %% ../nbs/01_utils.ipynb #cb0ba5f5
def add_stats(ax,
              df,
              value,
              group,
              test='t-test_ind',
              loc='inside',
              text_format='star',
              min_n=3,
              **kwargs):
    """
    If `value` is str:
        compare between groups (x=group, y=value)
    If `value` is list/tuple:
        compare among values within each group (x=group, hue='variable')
    """

    # -----------------------------
    # Case 1: value is a single column -> compare groups
    # -----------------------------
    if isinstance(value, str):
        # get x axis labels from the plot
        order = [t.get_text() for t in ax.get_xticklabels()]

        # Build all between-group pairs, but skip too-small samples
        pairs = []
        for g1, g2 in itertools.combinations(order, 2):
            d1 = df.loc[df[group] == g1, value].dropna()
            d2 = df.loc[df[group] == g2, value].dropna()
            if len(d1) >= min_n and len(d2) >= min_n:
                pairs.append((g1, g2))

        if len(pairs) == 0:
            print('No valid group-vs-group comparisons (check sample sizes).')
            return ax

        annotator = Annotator(ax, pairs, data=df, x=group, y=value, order=order)
        annotator.configure(test=test, text_format=text_format, loc=loc,
                            verbose=False, **kwargs)
        annotator.apply_and_annotate()
        return ax

    # -----------------------------
    # Case 2: value is list/tuple -> compare values within each group
    # -----------------------------
    if not isinstance(value, (list, tuple)):
        raise TypeError('`value` must be a column name (str) or a list/tuple of column names.')

    df_melted = df.melt(id_vars=group, value_vars=list(value)).dropna(subset=['value'])

    pairs = []
    for g in df_melted[group].unique():
        sub = df_melted[df_melted[group] == g]
        vars_in_group = sub['variable'].unique()

        for v1, v2 in itertools.combinations(vars_in_group, 2):
            d1 = sub.loc[sub['variable'] == v1, 'value']
            d2 = sub.loc[sub['variable'] == v2, 'value']
            if len(d1) >= min_n and len(d2) >= min_n:
                pairs.append(((g, v1), (g, v2)))

    if len(pairs) == 0:
        print('No valid within-group comparisons (check sample sizes).')
        return ax

    annotator = Annotator(ax, pairs, data=df_melted, x=group, y='value', hue='variable')
    annotator.configure(test=test, text_format=text_format, loc=loc,
                        verbose=False, **kwargs)
    annotator.apply_and_annotate()
    return ax
